#ifndef MDO_VERSION_H
#define MDO_VERSION_H

#define MDO_VERSION_MAJOR 0
#define MDO_VERSION_MINOR 1
#define MDO_VERSION_PATCH 0
#define MDO_VERSION_TEXT "0.1.0-dev"

#define MDO_CONFIG_SCHEMA_VERSION 1u
#define MDO_SESSION_SCHEMA_VERSION 3u
#define MDO_MODULE_ABI_VERSION 1u

#endif
