#include <stdio.h>
#include <string.h>

#include "internal.h"
#include "../../include/mdo/project_purge.h"

/* A client purge ID is separate from the per-HTTP correlation ID. All paths
 * are generated by the coordinator; the body contains no filesystem paths. */
static bool MdoApiPurgeCapture(const MdoApiContext* Context, char* Text, size_t Capacity)
{
    if ( Context->ParamCount != 1u || Context->Params[0].Size == 0u ||
         Context->Params[0].Size >= Capacity ||
         memchr(Context->Params[0].Data, '\0', Context->Params[0].Size) != NULL ) return false;
    memcpy(Text, Context->Params[0].Data, Context->Params[0].Size);
    Text[Context->Params[0].Size] = '\0';
    return true;
}

static cstr MdoApiPurgeOutcome(MdoHomePurgeOutcome Outcome)
{
    return Outcome == MDO_HOME_PURGE_COMMITTED ? "committed" :
        Outcome == MDO_HOME_PURGE_ABORTED ? "aborted" : "pending";
}

static bool MdoApiPurgeProjectValid(cstr Id)
{
    size_t i;
    if ( Id[0] == '\0' || Id[0] == '.' ) return false;
    for ( i = 0u; Id[i] != '\0'; ++i ) {
        unsigned char Ch = (unsigned char)Id[i];
        if ( !((Ch >= 'a' && Ch <= 'z') || (Ch >= 'A' && Ch <= 'Z') ||
                (Ch >= '0' && Ch <= '9') || Ch == '-' || Ch == '_' || Ch == '.') ) return false;
    }
    return true;
}

static xvalue* MdoApiPurgeValue(cstr Id, cstr Project, uint64 Revision, int64 CreatedAt,
    const MdoProjectPurgeResult* Result, cstr Outcome, int Accepted)
{
    xvalue* Data = xrtValueObject();
    bool Ok = Data != NULL && MdoApiValueSetString(Data, "purge_request_id", Id) &&
        MdoApiValueSetString(Data, "project_id", Project) &&
        MdoApiValueSetUInt(Data, "revision", Revision) &&
        MdoApiValueSetInt(Data, "created_at", CreatedAt) &&
        MdoApiValueSetString(Data, "outcome", Outcome) &&
        xrtValueObjectSetNew(Data, XRT_STR_LITERAL("accepted"),
            Accepted < 0 ? xrtValueNull() : xrtValueBool(Accepted != 0)) &&
        MdoApiValueSetBool(Data, "committed", Result->Committed) &&
        MdoApiValueSetBool(Data, "replayed", Result->Replayed) &&
        MdoApiValueSetBool(Data, "restart_required", Result->RestartRequired) &&
        MdoApiValueSetUInt(Data, "target_count", Result->Targets) &&
        MdoApiValueSetUInt(Data, "file_count", Result->Files) &&
        MdoApiValueSetUInt(Data, "directory_count", Result->Directories) &&
        MdoApiValueSetUInt(Data, "total_bytes", Result->Bytes) &&
        MdoApiValueSetUInt(Data, "schedule_count", Result->Schedules) &&
        MdoApiValueSetBool(Data, "selection_removed", Result->SelectionRemoved) &&
        MdoApiValueSetBool(Data, "global_draft_removed", Result->GlobalDraftRemoved) &&
        MdoApiValueSetBool(Data, "workspace_files_removed", false) &&
        MdoApiValueSetBool(Data, "shared_records_retained", true);
    if ( !Ok ) { xrtValueRelease(Data); Data = NULL; }
    return Data;
}

static void MdoApiPurgeReceiptResult(const MdoHomePurgeReceipt* Receipt,
    MdoProjectPurgeResult* Result, bool Replayed)
{
    MdoHomeSnapshot Home;
    memset(Result, 0, sizeof(*Result));
    Result->Committed = Receipt->Committed; Result->Replayed = Replayed;
    Result->Targets = Receipt->Request.Targets; Result->Files = Receipt->Request.Files;
    Result->Directories = Receipt->Request.Directories; Result->Bytes = Receipt->Request.Bytes;
    Result->Schedules = Receipt->Request.Schedules;
    Result->SelectionRemoved = Result->Committed && Receipt->Request.Selection;
    Result->GlobalDraftRemoved = Result->Committed && Receipt->Request.GlobalDraft;
    memset(&Home, 0, sizeof(Home)); Home.Size = sizeof(Home);
    Result->RestartRequired = !MdoHomeGetSnapshot(&Home) || Home.RestartRequired ||
        Receipt->Outcome == MDO_HOME_PURGE_PENDING;
}

bool MdoApiProjectPurgeResultRoute(MdoApiContext* Context)
{
    char Id[MDO_HOME_PURGE_REQUEST_CAPACITY];
    MdoHomePurgeReceipt Receipt;
    MdoProjectPurgeResult Result;
    bool Found;
    xvalue* Data;
    if ( !MdoApiPurgeCapture(Context, Id, sizeof(Id)) || !MdoHomePurgeRequestIdValid(Id) )
        return MdoApiReplyError(Context, 400u, "purge_request_invalid", "The purge request ID is invalid", NULL);
    if ( !MdoHomePurgeReceiptGet(Id, &Receipt, &Found) )
        return MdoApiReplyError(Context, 503u, "purge_result_unavailable", "The purge result could not be verified", NULL);
    if ( !Found ) return MdoApiReplyError(Context, 404u, "purge_request_not_found",
        "No accepted purge request or result is known; this does not authorize a new request", NULL);
    MdoApiPurgeReceiptResult(&Receipt, &Result, false);
    Data = MdoApiPurgeValue(Id, Receipt.Request.ProjectId, Receipt.Request.Revision,
        (int64)Receipt.Request.CreatedAt, &Result, MdoApiPurgeOutcome(Receipt.Outcome), 1);
    if ( Data == NULL ) return MdoApiReplyError(Context, 500u, "purge_result_unavailable",
        "The recorded purge result could not be serialized", NULL);
    return MdoApiReplySuccessTake(Context, 200u, Data, NULL);
}

static bool MdoApiProjectPurgeAction(MdoApiContext* Context, bool Cancel)
{
    char Project[MDO_PROJECT_ID_CAPACITY], Id[MDO_HOME_PURGE_REQUEST_CAPACITY];
    uint64 Revision = 0u;
    int64 CreatedAt = 0;
    int Precondition, Accepted = -1;
    bool Matches, Valid, Found, Replayed = false;
    xstrview RequestId;
    MdoApiJsonBody Body;
    MdoApiBodyStatus BodyStatus;
    MdoProjectPurgeStatus Status;
    MdoProjectPurgeResult Result;
    MdoHomePurgeReceipt Receipt;
    xwork_error Error;
    xvalue* Data;
    uint16 HttpStatus = 503u;
    cstr Code = "purge_unavailable", Outcome = "unknown";
    if ( !MdoApiPurgeCapture(Context, Project, sizeof(Project)) || !MdoApiPurgeProjectValid(Project) )
        return MdoApiReplyError(Context, 400u, "invalid_project_path", "The project ID is invalid", NULL);
    Precondition = MdoApiProjectExpectedRevision(Context, Project, &Revision, &Matches);
    if ( Precondition == 0 ) return MdoApiReplyError(Context, 428u, "precondition_required",
        "If-Match must contain the reviewed project ETag", NULL);
    if ( Precondition < 0 ) return MdoApiReplyError(Context, 400u, "invalid_precondition",
        "If-Match must use the form \"mdo-project-ID-N\"", NULL);
    if ( !Matches ) return MdoApiReplyError(Context, 412u, "revision_conflict",
        "The project ETag belongs to another project", NULL);
    if ( Revision == UINT64_MAX ) return MdoApiReplyError(Context, 422u, "purge_invalid",
        "The project revision cannot authorize a purge request", NULL);
    BodyStatus = MdoApiJsonBodyRead(Context, &Body);
    if ( BodyStatus != MDO_API_BODY_OK ) return MdoApiReplyBodyError(Context, BodyStatus);
    Valid = xrtValueType(Body.Value) == XVALUE_OBJECT && xrtValueCount(Body.Value) == 2u &&
        xrtValueGetString(xrtValueObjectGet(Body.Value, XRT_STR_LITERAL("purge_request_id")), &RequestId) &&
        RequestId.Size == 32u && memchr(RequestId.Data, '\0', RequestId.Size) == NULL &&
        xrtValueGetInt(xrtValueObjectGet(Body.Value, XRT_STR_LITERAL("created_at")), &CreatedAt) && CreatedAt > 0;
    if ( Valid ) {
        memcpy(Id, RequestId.Data, 32u); Id[32] = '\0';
        Valid = MdoHomePurgeRequestIdValid(Id);
    }
    MdoApiJsonBodyUnit(&Body);
    if ( !Valid ) return MdoApiReplyError(Context, 422u, "purge_invalid",
        "Expected a lowercase purge request ID and the reviewed project creation time", NULL);
    /* Do not GET the current definition here: it may be gone or replaced,
     * while a receipt remains valid. The coordinator checks fresh attempts. */
    xworkErrorInit(&Error); memset(&Result, 0, sizeof(Result));
    if ( !Cancel ) Status = MdoProjectPurgeExecuteRequested(Id, Project, Revision, CreatedAt, &Result, &Error);
    else if ( MdoHomePurgeRequestCancel(Id, Project, Revision, CreatedAt, &Receipt, &Replayed) ) {
        MdoApiPurgeReceiptResult(&Receipt, &Result, Replayed);
        Status = Result.RestartRequired ? MDO_PROJECT_PURGE_RESTART_REQUIRED : MDO_PROJECT_PURGE_OK;
        if ( Result.RestartRequired ) snprintf(Error.sMessage, sizeof(Error.sMessage),
            "The request result is recorded; restart before further writes");
    } else {
        const xerror* Cause = xrtGetError();
        MdoHomeSnapshot Home;
        Status = Cause != NULL && xrtErrorKind(Cause) == XERR_ARGUMENT ?
            MDO_PROJECT_PURGE_REQUEST_CONFLICT : MDO_PROJECT_PURGE_UNAVAILABLE;
        snprintf(Error.sMessage, sizeof(Error.sMessage), "%s",
            Cause != NULL && xrtErrorMessage(Cause) != NULL ? xrtErrorMessage(Cause) :
            "Cancellation could not be verified; query the same request ID");
        memset(&Home, 0, sizeof(Home)); Home.Size = sizeof(Home);
        Result.RestartRequired = !MdoHomeGetSnapshot(&Home) || Home.RestartRequired;
        if ( Result.RestartRequired && Status != MDO_PROJECT_PURGE_REQUEST_CONFLICT )
            Status = MDO_PROJECT_PURGE_RESTART_REQUIRED;
    }
    if ( MdoHomePurgeReceiptGet(Id, &Receipt, &Found) ) {
        Accepted = Found && strcmp(Receipt.Request.ProjectId, Project) == 0 &&
            Receipt.Request.Revision == Revision && Receipt.Request.CreatedAt == (uint64)CreatedAt;
        Outcome = Accepted ? MdoApiPurgeOutcome(Receipt.Outcome) : "not_accepted";
        /* Failed cancellation never invokes execution. Report original facts
         * even when cancellation lost to acceptance or needs recovery. */
        if ( Cancel && Accepted ) MdoApiPurgeReceiptResult(&Receipt, &Result, Replayed);
    }
    switch ( Status ) {
    case MDO_PROJECT_PURGE_OK: HttpStatus = 200u; Code = NULL; break;
    case MDO_PROJECT_PURGE_INVALID: HttpStatus = 422u; Code = "purge_invalid"; break;
    case MDO_PROJECT_PURGE_NOT_FOUND: HttpStatus = 404u; Code = "project_not_found"; break;
    case MDO_PROJECT_PURGE_REVISION_CONFLICT: HttpStatus = 412u; Code = "revision_conflict"; break;
    case MDO_PROJECT_PURGE_BUSY: HttpStatus = 409u; Code = "project_busy"; break;
    case MDO_PROJECT_PURGE_ABORTED: HttpStatus = 409u; Code = "project_purge_aborted"; break;
    case MDO_PROJECT_PURGE_RESTART_REQUIRED: HttpStatus = 503u; Code = "purge_restart_required"; break;
    case MDO_PROJECT_PURGE_REQUEST_CONFLICT: HttpStatus = 409u; Code = "purge_request_conflict"; break;
    default: break;
    }
    Data = MdoApiPurgeValue(Id, Project, Revision, CreatedAt, &Result, Outcome, Accepted);
    if ( Data == NULL ) return MdoApiReplyError(Context, 500u, "purge_result_unavailable",
        "The purge result could not be serialized; query the same request ID", NULL);
    if ( Code == NULL ) return MdoApiReplySuccessTake(Context, HttpStatus, Data, NULL);
    return MdoApiReplyErrorDetailsTake(Context, HttpStatus, Code, Error.sMessage, Data);
}

bool MdoApiProjectPurgeRoute(MdoApiContext* Context)
{
    return MdoApiProjectPurgeAction(Context, false);
}

bool MdoApiProjectPurgeCancelRoute(MdoApiContext* Context)
{
    return MdoApiProjectPurgeAction(Context, true);
}
